[project]
name = "intermidiate-ml"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "scienceplots>=2.1.1",
    "scikit-survival>=0.24.0",
    "seaborn>=0.13.2",
]
