[project]
name = "intermidiate-ml"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "lightning>=2.5.0.post0",
    "scikit-survival>=0.24.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
