on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      
      - uses: typst-community/setup-typst@v3
      
      - run: make compile
      
      - uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      
      - id: deployment
        uses: actions/deploy-pages@v4
