on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      
      - uses: typst-community/setup-typst@v3
      
      - run: make compile
      
      - run: |
          mkdir -p output
          find . -name '*.pdf' -exec cp {} output/ \;

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pdf
          publish_dir: ./output